### ISSUE TITLE
IOS  - cpp/js/lua 测试结果

### ISSUE THREAD

**Issue by tinybearc** [sdkbox/sdkbox-leadbolt-sample#1]
### leadbolt 版本：2.1.0.0

编译结果：
按钮：cache
输出:
Loading module with caching enabled for location: inapp
Module inapp cached successfully.
onModuleCached placement:inapp

按钮：show
点击cache后可点击show，会出现广告图片一张

**Comment by hugohuang1111** [comment]
pass
正常结果
